<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <description>Caritas Online Beratung: UploadService</description>

  <groupId>de.caritas.cob</groupId>
  <artifactId>uploadservice</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>UploadService</name>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.9</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>17</java.version>
    <keycloak.version>17.0.0</keycloak.version>
    <!-- force at least version 2.16 due to https://logging.apache.org/log4j/2.x/security.html -->
    <log4j.version>2.16.0</log4j.version>
    <openapi.generator.maven.version>7.11.0</openapi.generator.maven.version>
    <liquibase-maven-plugin.version>4.19.0</liquibase-maven-plugin.version>
    <spring.security.version>6.2.8</spring.security.version>
    <liquibase-core.version>4.9.1</liquibase-core.version>
    <jakarta.ws.rs-api.version>4.0.0</jakarta.ws.rs-api.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>de.flapdoodle.embed</groupId>
        <artifactId>de.flapdoodle.embed.mongo</artifactId>
        <version>3.4.11</version>
      </dependency>
      <dependency>
        <groupId>net.sf.ehcache</groupId>
        <artifactId>ehcache</artifactId>
        <version>2.10.9.2</version>
      </dependency>
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-inline</artifactId>
        <version>5.2.0</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-bom</artifactId>
        <version>${spring.security.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- Spring Boot dependencies -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-amqp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-cache</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
    </dependency>
    <dependency>
      <groupId>net.sf.ehcache</groupId>
      <artifactId>ehcache</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- Spring actuator  -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>

    <dependency>
      <groupId>jakarta.ws.rs</groupId>
      <artifactId>jakarta.ws.rs-api</artifactId>
      <version>${jakarta.ws.rs-api.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
    </dependency>

    <!-- Swagger/OpenApi dependencies -->
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>openapi-generator-maven-plugin</artifactId>
      <version>${openapi.generator.maven.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.sonatype.plexus</groupId>
      <artifactId>plexus-build-api</artifactId>
      <version>0.0.7</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>org.codehaus.plexus</groupId>
          <artifactId>plexus-utils</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
      <version>0.2.3</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
      <version>3.3.0</version>
    </dependency>

    <!-- Keycloak dependencies -->
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-spring-security-adapter</artifactId>
      <version>${keycloak.version}</version>
    </dependency>
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-spring-boot-starter</artifactId>
      <version>${keycloak.version}</version>
    </dependency>
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-admin-client</artifactId>
      <version>${keycloak.version}</version>
    </dependency>

    <!-- Lombok dependencies -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>2.6.0</version>
    </dependency>

    <!-- Apache Commons Lang -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>

    <!-- Apache Commons Collections -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-collections4</artifactId>
      <version>4.4</version>
    </dependency>

    <dependency>
      <groupId>com.github.jknack</groupId>
      <artifactId>handlebars</artifactId>
      <version>4.3.1</version>
    </dependency>

    <!-- Apache Commons Codec -->
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
    </dependency>

    <!-- JSON -->
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20230227</version>
    </dependency>

    <!-- Jsoup -->
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
      <version>1.14.2</version>
    </dependency>

    <!-- Liquibase -->
    <dependency>
      <groupId>org.liquibase</groupId>
      <artifactId>liquibase-maven-plugin</artifactId>
      <version>${liquibase-maven-plugin.version}</version>
    </dependency>
    <dependency>
      <groupId>org.liquibase</groupId>
      <artifactId>liquibase-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-to-slf4j</artifactId>
    </dependency>

    <!-- Tika -->
    <dependency>
      <groupId>org.apache.tika</groupId>
      <artifactId>tika-core</artifactId>
      <version>2.3.0</version>
    </dependency>

    <!-- MongoDB -->
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongo-java-driver</artifactId>
      <version>3.12.11</version>
    </dependency>

    <!-- Test scope dependencies -->
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>5.15.2</version>
      <scope>test</scope>
    </dependency>
    <!--    <dependency>-->
    <!--      <artifactId>powermock-module-junit4</artifactId>-->
    <!--      <groupId>org.powermock</groupId>-->
    <!--      <scope>test</scope>-->
    <!--      <version>2.0.2</version>-->
    <!--      <exclusions>-->
    <!--        <exclusion>-->
    <!--          <groupId>junit</groupId>-->
    <!--          <artifactId>junit</artifactId>-->
    <!--        </exclusion>-->
    <!--      </exclusions>-->
    <!--    </dependency>-->
    <dependency>
      <groupId>com.github.fridujo</groupId>
      <artifactId>rabbitmq-mock</artifactId>
      <version>1.1.1</version>
      <scope>test</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/net.javacrumbs.json-unit/json-unit -->
    <dependency>
      <groupId>net.javacrumbs.json-unit</groupId>
      <artifactId>json-unit</artifactId>
      <version>2.25.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <repositories>
    <repository>
      <id>1_maven.apache.org</id>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <url>https://repo.maven.apache.org/maven2</url>
      <layout>default</layout>
    </repository>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
  </repositories>

  <build>
    <finalName>${project.name}</finalName>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>

      <!-- OpenApi codegen maven plugin: generates api stubs -->
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>${openapi.generator.maven.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <configOptions>
                <interfaceOnly>true</interfaceOnly>
                <sourceFolder>/</sourceFolder>
                <useSpringBoot3>true</useSpringBoot3>
              </configOptions>
              <inputSpec>${project.basedir}/api/uploadservice.yaml</inputSpec>
              <generatorName>spring</generatorName>
              <apiPackage>${project.groupId}.${project.artifactId}.generated.api.controller
              </apiPackage>
              <modelPackage>${project.groupId}.${project.artifactId}.api.model</modelPackage>
              <generateSupportingFiles>true</generateSupportingFiles>
              <output>target/generated-sources</output>
            </configuration>
          </execution>
          <!-- Generate client API for user service -->
          <execution>
            <id>userservice-client-model</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <configOptions>
                <sourceFolder>/</sourceFolder>
                <library>resttemplate</library>
                <dateLibrary>java8</dateLibrary>
                <useSpringBoot3>true</useSpringBoot3>
              </configOptions>
              <inputSpec>${project.basedir}/services/userservice.yaml</inputSpec>
              <generatorName>java</generatorName>
              <generateApis>true</generateApis>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <apiPackage>${project.groupId}.${project.artifactId}.userservice.generated.web
              </apiPackage>
              <modelPackage>
                ${project.groupId}.${project.artifactId}.userservice.generated.web.model
              </modelPackage>
            </configuration>
          </execution>
          <!-- Generate client API for statistics service -->
          <execution>
            <id>statisticsservice-client-model</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <configOptions>
                <sourceFolder>/</sourceFolder>
                <library>resttemplate</library>
                <dateLibrary>java8</dateLibrary>
                <useSpringBoot3>true</useSpringBoot3>
              </configOptions>
              <inputSpec>${project.basedir}/services/statisticsservice.yaml</inputSpec>
              <generatorName>java</generatorName>
              <generateApis>true</generateApis>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <modelPackage>
                ${project.groupId}.${project.artifactId}.statisticsservice.generated.web.model
              </modelPackage>
            </configuration>
          </execution>
          <execution>
            <id>tenantservice-client-model</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <configOptions>
                <sourceFolder>/</sourceFolder>
                <library>resttemplate</library>
                <dateLibrary>java8</dateLibrary>
                <useSpringBoot3>true</useSpringBoot3>
              </configOptions>
              <inputSpec>${project.basedir}/services/tenantservice.yaml</inputSpec>
              <generatorName>java</generatorName>
              <generateApis>true</generateApis>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <apiPackage>
                ${project.groupId}.${project.artifactId}.tenantservice.generated.web
              </apiPackage>
              <modelPackage>
                ${project.groupId}.${project.artifactId}.tenantservice.generated.web.model
              </modelPackage>
            </configuration>
          </execution>
          <!-- Generate models for RocketChat -->
          <execution>
            <id>rocketchat-client-model</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <configOptions>
                <sourceFolder>/</sourceFolder>
                <library>resttemplate</library>
                <dateLibrary>java8</dateLibrary>
                <useSpringBoot3>true</useSpringBoot3>
                <!--suppress UnresolvedMavenProperty -->
                <additionalModelTypeAnnotations>@lombok.AllArgsConstructor @lombok.Builder
                </additionalModelTypeAnnotations>
              </configOptions>
              <inputSpec>${project.basedir}/services/rocketchat.yaml</inputSpec>
              <generatorName>java</generatorName>
              <generateApis>false</generateApis>
              <generateSupportingFiles>false</generateSupportingFiles>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <skipValidateSpec>true</skipValidateSpec>
              <modelPackage>
                ${project.groupId}.${project.artifactId}.rocketchat.generated.web.model
              </modelPackage>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Code style check -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>3.6.0</version>
        <executions>
          <execution>
            <id>validate</id>
            <phase>validate</phase>
            <configuration>
              <configLocation>google_checks_light.xml</configLocation>
              <failsOnError>true</failsOnError>
              <consoleOutput>true</consoleOutput>
              <failOnViolation>true</failOnViolation>
              <logViolationsToConsole>true</logViolationsToConsole>
              <violationSeverity>warning</violationSeverity>
              <includeTestSourceDirectory>true</includeTestSourceDirectory>
            </configuration>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin
        </artifactId> <!-- surefire plugin version managed by Spring Boot -->
        <configuration>
          <skipTests>true</skipTests>
        </configuration>
        <executions>
          <execution>
            <id>unit-tests</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <skipTests>false</skipTests>
              <includes>
                <include>de/caritas/cob/uploadservice/api/tenant/TenantResolverServiceTest.java
                </include>
                <include>
                  de/caritas/cob/uploadservice/api/tenant/AccessTokenTenantResolverTest.java
                </include>
                <include>de/caritas/cob/uploadservice/api/tenant/SubdomainTenantResolverTest.java
                </include>
                <include>
                  de/caritas/cob/uploadservice/api/tenant/CustomHeaderTenantResolverTest.java
                </include>
                <include>
                  de/caritas/cob/uploadservice/api/tenant/TechnicalUserTenantResolverTest.java
                </include>
                <include>de/caritas/cob/uploadservice/filter/HttpTenantFilterTest.java</include>
                <include>de/caritas/cob/uploadservice/filter/SubdomainExtractorTest.java</include>
              </includes>
            </configuration>
          </execution>
          <execution>
            <id>integration-tests</id>
            <phase>integration-test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <skipTests>false</skipTests>
              <includes>
                <include>de/caritas/cob/uploadservice/api/controller/ActuatorControllerIT.java
                </include>
                <include>
                  de/caritas/cob/uploadservice/api/service/LiveEventNotificationServiceIT.java
                </include>
              </includes>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.23.0</version>
        <configuration>
          <java>
            <toggleOffOn/>
            <googleJavaFormat>
              <version>1.15.0</version>
              <style>GOOGLE</style>
            </googleJavaFormat>
          </java>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>compile</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>local</id>
      <properties>
        <activeSpringProfile>local</activeSpringProfile>
      </properties>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
    <profile>
      <id>dev</id>
      <properties>
        <activeSpringProfile>dev</activeSpringProfile>
      </properties>
    </profile>
    <profile>
      <id>prod</id>
      <properties>
        <activeSpringProfile>prod</activeSpringProfile>
      </properties>
    </profile>
  </profiles>

</project>
