openapi: 3.0.1
info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1
paths:
  /uploads/messages/key:
    post:
      tags:
        - upload-controller
      summary: 'Update the master-key fragment for the Session-Key [Authorization:
        Role: technical]'
      operationId: updateKey
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/MasterKeyDto'
        required: true
      responses:
        202:
          description: ACCEPTED - key was successfully inserted
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid role/authorization
        409:
          description: CONFLICT - master-key is already set
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: []
  /uploads/new/{roomId}:
    post:
      tags:
        - upload-controller
      summary: 'Upload a file and send a message to a Rocket.Chat room [Authorization:
        Role: user, anonymous, consultant]'
      operationId: uploadFileToRoom
      parameters:
        - name: roomId
          in: path
          description: Rocket.Chat room id
          required: true
          schema:
            type: string
        - name: RCToken
          in: header
          required: true
          schema:
            type: string
        - name: RCUserId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
                - sendNotification
              properties:
                msg:
                  type: string
                  description: A text message
                description:
                  type: string
                  description: A description of the file
                tmId:
                  type: string
                  description: The thread message id (if you want upload a file to
                    a thread)
                fileHeader:
                  type: string
                  description: Starting bytes of file which includes mimetype for verification
                t:
                  type: string
                  description: Type of message
                  example: "e2e"
                file:
                  type: string
                  description: File to upload
                  format: binary
                sendNotification:
                  type: string
                  description: Flag, whether an email notification should be sent
                    or not (true/false)
        required: true
      responses:
        201:
          description: CREATED - upload was successfully performed
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid role/authorization
        413:
          description: REQUEST ENTITY TOO LARGE - Maximum upload size exceeded
        415:
          description: UNSUPPORTED MEDIA TYPE - Type of uploaded file is not allowed
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: []
  /uploads/feedback/new/{feedbackRoomId}:
    post:
      tags:
        - upload-controller
      summary: 'Upload a file and send a message to to a Rocket.Chat feedback room
        [Authorization: authority for feedback chat]'
      operationId: uploadFileToFeedbackRoom
      parameters:
        - name: feedbackRoomId
          in: path
          description: Rocket.Chat room id
          required: true
          schema:
            type: string
        - name: RCToken
          in: header
          required: true
          schema:
            type: string
        - name: RCUserId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
                - sendNotification
              properties:
                msg:
                  type: string
                  description: A text message
                description:
                  type: string
                  description: A description of the file
                tmId:
                  type: string
                  description: The thread message id (if you want upload a file to
                    a thread)
                file:
                  type: string
                  description: File to upload
                  format: binary
                sendNotification:
                  type: string
                  description: Flag, whether an email notification should be sent
                    or not (true/false)
        required: true
      responses:
        201:
          description: CREATED - upload was successfully performed
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid role/authorization
        413:
          description: REQUEST ENTITY TOO LARGE - Maximum upload size exceeded
        415:
          description: UNSUPPORTED MEDIA TYPE - Type of uploaded file is not allowed
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: []

components:
  schemas:
    MasterKeyDto:
      type: object
      required:
        - masterKey
      properties:
        masterKey:
          type: string
          example: "sdj8wnFNASj324!ksldf9"

  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
